### ISSUE TITLE
Problem accessing new buckets

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-amazon-s3#17]
[Customer reported](https://secure.helpscout.net/conversation/125779417/17728/) problem accessing new buckets. She gets this message:
`S3::getBucket(): [TemporaryRedirect] Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests. - /home/ociacia/buyourobot.com/www/wp-content/plugins/edd-amazon-s3/s3.php:441 Code: 0`

I've confirmed the same thing happens to be locally.

If I try to upload to the new bucket, I get this:

![image](https://cloud.githubusercontent.com/assets/1254870/10151652/ca734ad6-6617-11e5-8b0a-567092d8233a.png)

If I downgrade to the previous version, I see the exception error when trying to upload:
```
Fatal error: Uncaught exception 'S3Exception' with message 'S3::putObject(): [TemporaryRedirect] Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.' in /wp-content/plugins/edd-amazon-s3/s3.php:683

Stack trace: #0 /wp-content/plugins/edd-amazon-s3/s3.php(683): S3::__triggerError('S3::putObject()...', '/Users/john/Sites...', 683)

#1 /wp-content/plugins/edd-amazon-s3/edd_s3.php(486): S3::putObject(Array, 'edd-new-bucket', 'IMG_6967.jpg')

#2 /wp-content/plugins/edd-amazon-s3/edd_s3.php(469): EDD_Amazon_S3::upload_file(Array)

#3 [internal function]: EDD_Amazon_S3->upload_handler(Array)

#4 /wp-includes/plugin.php(503): call_user_func_array(Array, Array)

#5 /wp-content/plugins/easy-digital-downloads/includes/actions.php(25): do_action('edd_s3_upload', Array) 

#6 [internal function]: edd_get_actions('') #7 /Users/john/Sites/e in /wp-content/plugins/edd-amazon-s3/s3.php on line 683
```

Customer reports downgrading to 2.1.2 fixed it for her. I have not tested and confirmed that or any other versions in between.

**Comment by mindctrl** [comment]
Steps to reproduce:

- Log into Amazon S3 console
- Create new bucket with proper permissions
- Go back to EDD site and try to access or upload to the new bucket.

**Comment by pippinsplugins** [comment]
Old buckets still work fine?

**Comment by mindctrl** [comment]
@pippinsplugins yes

**Comment by mindctrl** [comment]
I am no longer seeing this. It must have been a temporary glitch with Amazon. I'm going to email the customer back to see if I can get confirmation from her.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
Customer reports she still has this problem.

**Comment by mindctrl** [comment]
I've seen this several times since. Basically there's a waiting period while the bucket DNS stuff propagates I think. Maybe we can find a workaround for this.

**Comment by geniuspro** [comment]
Hello.
I've this issue. How can i fix it? Suggest any solution @mindctrl @pippinsplugins 
Thanks

**Comment by pippinsplugins** [comment]
@geniuspro at the moment the solution is to just be patient. They will show up after a period of time.

**Comment by geniuspro** [comment]
@pippinsplugins I found easy solution for this issue. I've created new bucket on my S3 server and add 
"Any Authenticated AWS User" permission. after works fine for me.

**Comment by pippinsplugins** [comment]
Great!
