### ISSUE TITLE
Download method not set when using EDD Software Licensing

### ISSUE THREAD

**Issue by davekiss** [easydigitaldownloads/edd-amazon-s3#18]
The introduction of https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/191 now bypasses setting the download method to redirect because EDD Amazon S3 hooks into a filter that is never called when used in conjunction with the current version of EDD Software Licensing:

https://github.com/easydigitaldownloads/edd-amazon-s3/blob/0413f1cf22474caab12aae0238a24083a5157e42/edd_s3.php#L179

There needs to be a way to verify that the download is an S3 download when processing the download through EDD Software Licensing.

**Comment by pippinsplugins** [comment]
@davekiss What's the behavior you're seeing? Do you have the Download Method set to `Forced`? Are those updates through S3 failing?

**Comment by webaware** [comment]
@pippinsplugins  FWIW, I had to change my store download method to `Redirect` to get S3 downloads working.

**Comment by cklosowski** [comment]
@davekiss @pippinsplugins @webaware could you guys take a look at the changes I made above, and let me know if this should take care of your needs?

In testing this makes it so you can leave 'forced' on the main download type and lets S3 pass through with the redirect.

**Comment by cklosowski** [comment]
Also added some verifications to the `generate_url` method, as it wasn't doing any sanitization checks on the data before trying to use it.

**Comment by webaware** [comment]
Just downloaded the zip for this branch and tried it with `Forced`, no dice. My symptoms with this are the following in the NginX log when I try to install an update into another stand-alone site on the same server:

`rewrite or internal redirection cycle while redirect to named location`

I get that with `Forced` and the package delivered from Amazon S3. With `Redirect` it works normally. So it seems that it's not forcing `Redirect`.

**Comment by webaware** [comment]
FWIW, I don't actually need `Forced` since my downloads will all be hosted externally, either on S3 or WordPress.org plugin repo. I only hit this problem because it wasn't documented to set `Redirect`. Might still be better fixed though, I guess.

**Comment by cklosowski** [comment]
@webaware yes, that means my fix didn't work correclty the goal is to have files found to be hosted on Amazon S3 set the `Redirect` method for that request even with the setting on `Forced`. Let me work on this a bit more this afternoon and I'll get some stuff pushed up.

**Comment by Asif2BD** [comment]
This problem still exists when you are using EDD+SL+S3, happened to us in nginx server, not sure about Apache.

**Comment by SDavisMedia** [comment]
Trying to replicate this before testing and I'm getting slightly confusing results.

On `master` for EDD, SL, and S3, I seem to be getting an error when trying to download an update:
![image 2018-03-09 at 3 14 21 pm](https://user-images.githubusercontent.com/2359131/37234901-68c704aa-23af-11e8-8fbe-42d7bec3f7d0.png)

I **only** get this error when I try to replicate on my computer running Local [by Flywheel], as it runs Nginx on PHP 7.1.4. Conditions for this error:

* happens on BOTH S3 `master` and S3 `issue/18-2`
* only happens with files that are hosted on S3 (confirmed that files uploaded to WP work fine)
* I cannot replicate this on my computer running Apache and PHP 7.1.3

What I did to cause the error was set up a licensed product, purchase it, activate its license, then used the following request in my browser as if I was doing an update:

```
http://edd.dev/?edd_action=get_version&item_id=461&license=5a6e8c2a416b1f35972898a936918d58&url=http://edd.dev
```

That returns:

```
{"new_version":"1.0","stable_version":"1.0","name":"Sample Plugin","slug":"sample-plugin","url":"http:\/\/edd.dev\/downloads\/sample-plugin\/?changelog=1","last_updated":"2018-03-09 23:03:02","homepage":"http:\/\/edd.dev\/downloads\/sample-plugin\/","package":"http:\/\/edd.dev\/edd-sl\/package_download\/MTUyMDcyNDY0NDo1YTZlOGMyYTQxNmIxZjM1OTcyODk4YTkzNjkxOGQ1ODo0NjE6Zjg1NWFiMzE5YWNlNmVlYmQzNTQzYjJiYmNkMzRhNGQ6aHR0cEAvL2VkZC5kZXY6MA==","download_link":"http:\/\/edd.dev\/edd-sl\/package_download\/MTUyMDcyNDY0NDo1YTZlOGMyYTQxNmIxZjM1OTcyODk4YTkzNjkxOGQ1ODo0NjE6Zjg1NWFiMzE5YWNlNmVlYmQzNTQzYjJiYmNkMzRhNGQ6aHR0cEAvL2VkZC5kZXY6MA==","sections":"a:2:{s:11:\"description\";s:383:\"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor malesuada vehicula. Duis eget laoreet nunc. Duis tristique sapien felis, sit amet accumsan nulla fermentum posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor malesuada vehicula. Duis eget laoreet nunc. Duis tristique sapien felis, sit amet accumsan nulla fermentum posuere.<\/p>\n\";s:9:\"changelog\";s:0:\"\";}","banners":"a:2:{s:4:\"high\";s:0:\"\";s:3:\"low\";s:0:\"\";}"}
```

I then used the package/download links to try the download. With the configuration mentioned previously, I got the error. With all other configurations and environments, I could not replicate.

Just dumping this information here as I'm not sure if the error is the same what this PR addresses or not.

**Comment by pippinsplugins** [comment]
I haven't replicated your error @SDavisMedia, but I did trigger a different fatal error:

Fatal error: Uncaught InvalidArgumentException: Found 2 errors while validating the input provided for the GetObject operation: [Key] is missing and is a required parameter [Key] expected string length to be >= 1, but found string length of 0 in /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Api/Validator.php:65 Stack trace: #0 /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Middleware.php(79): Aws\Api\Validator->validate('GetObject', Object(Aws\Api\StructureShape), Array) #1 /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(421): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL) #2 /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(444): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL) #3 /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(378): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL) #4 /var/www/htm in /var/www/html/wp/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65

**Comment by pippinsplugins** [comment]
But of course now i cannot re-replicate my own error. Might have been related to a wifi connection problem I was having while testing.

It's now all working fine for me, both on `master` and `issue/18-2`.

**Comment by SDavisMedia** [comment]
@pippinsplugins can you share details about your testing environment please? Did you test on Nginx?

**Comment by pippinsplugins** [comment]
It's localhost running apache only (I can test nginx tomorrow).
